#!/bin/sh



echo "Update system";
sudo dnf update;



echo "Install Emacs24";
sudo dnf install -y emacs24;
echo "Install Sublime-Text-3";
sudo add-apt-repository ppa:webupd8team/sublime-text-3;
sudo dnf install -y sublime-text-installer;



echo "Install SSH";
sudo dnf install -y ssh;
echo "Install Git";
sudo dnf install -y git;



echo "Install Unetbootin";
sudo dnf install -y unetbootin;
echo "Install rar";
sudo dnf install -y rar;
echo "Install C++";
sudo dnf install -y g++;
echo "Install Gparted";
sudo dnf install -y gparted;
echo "Install LibreOffice";
sudo dnf install -y libreoffice;
echo "Install VirtualBox";
sudo dnf install -y virtualbox;
echo "Install Синтезатор речи";
sudo dnf install -y festival festvox-ru;
echo "Install wine";
sudo dpkg --add-architecture i386; 
sudo add-apt-repository ppa:wine/wine-builds; 
sudo dnf install -y --install-recommends winehq-devel;



echo "Update system";
sudo dnf update;