#!/bin/sh


echo "Update system";
sudo dnf update;


echo "Install Netbeans";
sudo dnf install -y netbeans;
echo "Install JFX";
sudo dnf install -y openjfx;
echo "Install Oracle Java8";
sudo add-apt-repository ppa:webupd8team/java;
sudo dnf install -y oracle-java8-installer;
echo "Install Maven";
sudo dnf install -y maven;


echo "Update system";
sudo dnf update;

