#!/bin/sh


echo "Update system";
sudo dnf update;


echo "Install C++";
sudo dnf install -y g++;


echo "Install QT";
sudo dnf install -y qt5;
sudo dnf install -y qt5-default;
echo "Install QTCreator";
sudo dnf install -y qtcreator;
sudo dnf install -y qtbase5-examples qtdeclarative5-examples;
echo "Install QtMultimedia"
sudo dnf install -y qtmultimedia5-dev; 
echo "Install PDF libery for QT, Poppler"
sudo dnf install -y libpoppler-qt5-1;
sudo dnf install -y libpoppler-qt5-dev;
#Exemple
#LIBS += -L/usr/local/lib -lpoppler-qt5

echo "Update system";
sudo dnf update;

