#!/bin/sh


echo "Update system";
sudo apt-get update;



echo "Install Netbeans";
sudo apt-get install -y netbeans;
echo "Install JFX";
sudo apt-get install -y openjfx;
echo "Install Oracle Java8";
sudo add-apt-repository ppa:webupd8team/java;
sudo apt-get install -y oracle-java8-installer;
echo "Install Maven";
sudo apt-get install -y maven;

echo "Update system";
sudo apt-get update;
